service: serverless-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:177293166426:table/TodoTable

functions:
  newTodo:
    handler: src/addTodo.handler
    events:
      - http:
          path: /
          method: post
  fetchTodos:
    handler: src/fetchTodos.handler
    events:
      - http:
          path: /todos
          method: get
  fetchTodo:
    handler: src/fetchTodo.handler
    events:
      - http:
          path: /todo/{id}
          method: get
  updateTodo:
    handler: src/updateTodo.handler
    events:
      - http:
          path: /todo/{id}
          method: PUT
          cors: true


resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
